Screed/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user_redirect/', views.user_redirect, name='user_redirect'),
    path('traveler/<int:traveler_id>/', views.traveler, name='traveler'),
    path('choice/<int:traveler_id>/<int:choice_id>/', views.choice, name='choice'),
    path('new/<int:user_id>/<int:parent_id>/', views.new, name='new'),
    path('new_item/<int:user_id>/', views.new_item, name='new_item'),
    path('new_traveler/<int:user_id>/', views.new_traveler, name='new_traveler'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout', auth_views.LogoutView.as_view(),name='logout'),
]

corn_hacks_2022/urls.py
from django.contrib import admin
from django.urls import path, include
from Screed import views as Screed_views


urlpatterns = [
    path('screed/', include('Screed.urls')),
    path('admin/', admin.site.urls),

    path('', Screed_views.index, name='index'),
    path('account/', include('users_app.urls')),
    
    # path('accounts/', include("django.contrib.auth.urls")),
   

]

Screed/models.py
from django.db import models
from django.contrib.auth.models import User

# class User(models.Model):
#     name = models.CharField(max_length=127)
#     email = models.EmailField()
#     score = models.IntegerField(default=1)

#     def __str__(self):
#         return self.name

class StatDefinition(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    authors = models.ManyToManyField(User)

    def __str__(self):
        return self.name

# The item description does not change. If there is an edit, a new item description is made.
class ItemDefinition(models.Model):
    ATTACK = 'A'
    DEFENSE = 'D'
    SUPPORT = 'S'
    BURDEN = 'B'
    TYPES = [
        (ATTACK, 'Attack'),
        (DEFENSE, 'Defense'),
        (SUPPORT, 'Support'),
        (BURDEN, 'Burden'),
    ]

    # An id for the item that does not change across versions.
    tag = models.IntegerField(null=True)
    name = models.CharField(max_length=255)
    type = models.CharField(
        max_length=1,
        choices=TYPES,
        default=SUPPORT,
    )
    description = models.TextField()
    authors = models.ManyToManyField(User)
    quantity = models.IntegerField(
        default=0
    )
    power_type = models.ForeignKey(
        StatDefinition,
        on_delete=models.SET_NULL,
        null=True,
        related_name='power_item'
    )
    power = models.IntegerField(default=0)
    cost_type = models.ForeignKey(
        StatDefinition,
        on_delete=models.SET_NULL,
        null=True,
        related_name='cost_item'
    )
    cost = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    

class Node(models.Model):
    title = models.CharField(max_length=511)
    text = models.TextField()
    authors = models.ManyToManyField(User)
    positive = models.IntegerField(default=1)
    negative = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Traveler(models.Model):
    name = models.CharField(max_length=127)
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True
    )
    node = models.ForeignKey(
        Node,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.name

class Stat(models.Model):
    definition = models.ForeignKey(
        StatDefinition,
        on_delete=models.CASCADE,
        null=True
    )
    owner = models.ForeignKey(
        Traveler,
        on_delete=models.CASCADE,
        null=True
    )
    score = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.definition} - {self.owner}'

class Item(models.Model):
    definition = models.ForeignKey(
        ItemDefinition,
        on_delete=models.CASCADE,
        null=True
    )
    quantity = models.IntegerField(
        default=0
    )
    owner = models.ForeignKey(
        Traveler,
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return f'{self.definition} - {self.owner}'

class Edit(models.Model):
    title = models.CharField(max_length=511)
    description = models.TextField()
    text = models.TextField()
    author = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    positive = models.IntegerField(default=1)
    negative = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Reward(models.Model):
    node = models.ForeignKey(
        Node,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    item = models.ForeignKey(
        ItemDefinition,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    def __str__(self):
        return f'{self.item} <- {self.node}'

class Check(models.Model):
    title = models.CharField(max_length=511)
    success_message = models.TextField()
    success_target = models.ForeignKey(
        Node,
        on_delete=models.SET_NULL,
        null=True,
        related_name='from_success'
    )
    failure_message = models.TextField()
    failure_target = models.ForeignKey(
        Node,
        on_delete=models.SET_NULL,
        null=True,
        related_name='from_failure'
    )
    stat_type = models.ForeignKey(
        StatDefinition,
        on_delete=models.SET_NULL,
        null=True
    )
    value = models.IntegerField(default=1)
    item_requirement = models.ForeignKey(
        ItemDefinition,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title

class Choice(models.Model):
    text = models.TextField()
    parent = models.ForeignKey(
        Node,
        on_delete=models.SET_NULL,
        null=True
    )
    target = models.ForeignKey(
        Node,
        on_delete=models.SET_NULL,
        null=True,
        related_name='reached_by'
    )
    choice_check = models.ForeignKey(
        Check,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='parent'
    )

    def __str__(self):
        return self.text

templates/index.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="Navbar" id="myTopnav">
        <a class="active" href="#Home"> Home</a>
        <a href="#Services"> Services</a>
        <a href="#Contacts"> Contacts</a>
      </div>
    </div>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="center"> Logged in as {{ user.username }}</div> 
        <a href="{% url 'logout' %}"><button type="submit">Logout</button></a>
    </div>
    {% else %}
    <a href="{% url 'login' %}"><button type="submit">Login</button></a>
    <a href="{% url 'register' %}"><button type="submit">Register</button></a>
    {% endif %}
</body>
</html>

templates/invalid.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ traveler.name }} - {{ traveler.node.title }}</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="left">
        <h1>{{ traveler.name }}</h1>
        <h2>Stats:</h2>
        <ul>
            {% for stat in traveler.stat_set.all %}
                <li>{{ stat.definition.name }}: {{ stat.score }}</li>
            {% endfor %}
        </ul>
        <h2>Items:</h2>
        <ul>
            {% for item in traveler.item_set.all %}
                <li>{{ item.definition.name }}{% if item.quantity > 0 %}: {{ item.quantity }}{% endif %}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="center">
        <h2>Invalid choice!</h2>
        <a href="{% url 'traveler' traveler.id %}">Back</a>
    </div>
</body>
</html>

templates/new.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Node</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <form action="/screed/new/{{user.id}}/{{parent.id}}/" method="post">
        {% csrf_token %}
        <h2>From:</h2>
        <h3>{{ parent.title }}</h3>
        <p>{{ parent.text }}</p>
        <h2>Choice:</h2>
        {{ choice_form }}
        <h2>Check:</h2>
        {% if has_check %}
        {{ check_form }}
        {% endif %}
        <h2>Story Node:</h2>
        {% if has_check %}
        <h3>Success</h3>
        {% endif %}
        {{ node_form }}
        {% if has_check %}
        <h3>Failure</h3>
        {{ failure_form }}
        {% endif %}
        <h2>Reward:</h2>
        {{ reward_form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/new_item.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Item</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <form action="/screed/new_item/{{user.id}}/" method="post">
        {% csrf_token %}
        <h2>Item:</h2>
        {{ item_form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/new_traveler.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Item</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <form action="/screed/new_traveler/{{user.id}}/" method="post">
        {% csrf_token %}
        <h2>Traveler:</h2>
        {{ traveler_form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/traveler.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ traveler.name }} - {{ traveler.node.title }}</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="left">
        <h1>{{ traveler.name }}</h1>
        <h2>Stats:</h2>
        <ul>
            {% for stat in traveler.stat_set.all %}
                <li>{{ stat.definition.name }}: {{ stat.score }}</li>
            {% endfor %}
        </ul>
        <h2>Items:</h2>
        <ul>
            {% for item in traveler.item_set.all %}
                <li>{{ item.definition.name }}{% if item.quantity > 0 %}: {{ item.quantity }}{% endif %}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="right">
        <a href="{% url 'user' traveler.user.id %}">{{ traveler.user }}</a>
    </div>

    <div class="center">
        <h2>{{ traveler.node.title }}</h2>
        <p>{{ traveler.node.text }}</p>

        <ul>
            {% for choice in traveler.node.choice_set.all %}
                <li><a href="{% url 'choice' traveler.id choice.id %}">{{ choice.text }}</a></li>
            {% endfor %}
        </ul>

        {% if False %}<div><div>+ {{ traveler.node.positive }}</div><div>- {{ traveler.node.negative }}</div></div>{% endif %}
        <a href="{% url 'new' traveler.user.id traveler.node.id %}">New Path</a>
    </div>
</body>
</html>

templates/user.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile - {{ user.username }}</title>
    <link  href="{% sass_src 'style.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="right">
        <a href="{% url 'logout' %}">Logout</a>
    </div>
    <div class="center">
        <h1>{{ user.username }}</h1>
        <ul>
            {% for traveler in user.traveler_set.all %}
                <li><a href="{% url 'traveler' traveler.id %}">{{ traveler.name }}</a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'new_traveler' user.id %}">New Traveler</a>
    </div>
</body>
</html>